### ISSUE TITLE
Code to generate prior point clouds

### ISSUE THREAD

**Issue by kannwism** [leo94-hk/SGPA#10]
Hi there,

first of all, thank you for your fascinating work!

In the paper I read this part:

> For the prior point cloud, we train an autoencoder network on the ShapeNet dataset [3], and then we
feed the average embedding of all instances that belong to
the same category into the trained decoder to get the prior
point cloud for this category. 

I couldn't find code for this step in the repository. Did I miss something? Would it be possible to upload this part too? Reason being that I'd like to train with further object categories.

Thanks!

**Comment by ck-kai** [comment]
Hi, thanks for your interest in our work.

We follow the same scheme with [object-deformnet](https://github.com/mentian/object-deformnet) to generate the category-level prior point cloud. We just re-train the auto-encoder in our experiments. You can directly refer to the repo for more details.

**Comment by kannwism** [comment]
Ah I understand, thank you for the link!
