### ISSUE TITLE
Question about the value of train_steps

### ISSUE THREAD

**Issue by winka9587** [leo94-hk/SGPA#8]
Thanks for sharing good work.
I tried to train SGPA on **CAMERA+Real**. However, it seems that the something wrong in sampling CAMERA dataset when running **train.sh**. 
`raise ValueError: Sample larger than population or is negative`

This error means that the value of `3*n_repeat*real_len` is larger than `len(camera_indices)` 
`                data_list = random.sample(camera_indices, 3*n_repeat*real_len) + real_indices*n_repeat` in [train.py line 100](https://github.com/leo94-hk/SGPA/blob/26bde2812bfa00112b9c33d847b6d448c54de98f/train.py#L100l)

The output of related variables as follows:
![image](https://user-images.githubusercontent.com/23701529/166878188-7f2d4bbc-9c17-4bbb-a0aa-b1440b66c320.png)

For comparison, I run the corresponding code in SPD, output as follows:
![image](https://user-images.githubusercontent.com/23701529/166878371-5997cc48-9ff3-4a78-9184-261cefaef028.png)

It seems that the difference of **train_steps** and **batch_size** makes the value of train_size bigger than `len(camera_indices)`,   and the influence of **train_steps** is the main one(SGPA:8000, SPD:1500)
I use dataset preprocess code from SPD, the reason I can think of is that the dataset is different, or the value of train_steps is wrong. 
Did I miss anything?
Hope someone provide the output of the values I listed. 
:)

**Comment by touchthefish233** [comment]
Hi, I have the same problem, have you solved it?
